export const journalEntries = [
  {
    id: 1,
    date: "March 21",
    title: "Arm-wrestling, music-making, flirtatious-murderers for hire!",
    summary:
      "Meeting for the first time in a tavern in Termalaine, our heroes take measure of each other and find quick work for fair pay.",
    url: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    startPoint: "Termalaine",
    endPoint: "Tavern",
    loot: null,
  },
  {
    id: 2,
    date: "March 28",
    title: "The Gang Commits Premeditated Murder...",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
    startPoint: "Tavern",
    endPoint: "Tavern",
    lootFound: ['100GP', 'bone scrimshaw', ]
  },
  {
    id: 3,
    date: "April 18",
    title: "Can't Hurt Me",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/10425061-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: null,
    lootFound: 5,
  },
  {
    id: 4,
    date: "April 25",
    title: "Deep Work",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/10088428-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: 19,
    lootFound: 4.5,
  },
  {
    id: 5,
    date: "May 2",
    title: "The 10X Rule",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/9978588-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: null,
    lootFound: 5,
  },
  {
    id: 6,
    date: "May 9",
    title: "Heart Gets a Proper Blood Bath",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/7737110-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: 12.5,
    lootFound: 5,
  },
  {
    id: 7,
    date: "May 16",
    title: "Rich Dad Poor Dad",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/2380224-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: 10,
    lootFound: 4,
  },
  {
    id: 8,
    date: "May 23",
    title: "Cashflow Quadrant",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/1954899-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: 17.95,
    lootFound: 4.5,
  },
  {
    id: 9,
    date: "May 25",
    title: "48 Laws of Power Summary",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/8906626-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: 19.95,
    lootFound: 4.5,
  },
  {
    id: 10,
    date: "May 30",
    title: "The 5 Second Rule",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/8114155-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: null,
    lootFound: 5,
  },
  {
    id: 11,
    date: "June 13",
    title: "How to Win Friends & Influence People",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: 20,
    lootFound: 5,
  },
  {
    id: 12,
    date: "July 11",
    title: "Mastery",
    summary: "",
    url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
    startPoint: "Tourmalaine",
    endPoint: "Lonely Wood",
    lootFound: 4.5,
  },
];
